// prisma/seed-data.ts
// Shared seed data for job categories, resume examples, and skill suggestions

export const jobCategories = [
  {
    name: 'Information Technology',
    slug: 'information-technology',
    description: 'Technology professionals building and maintaining digital systems',
    icon: '💻',
    color: '#3B82F6',
    metaTitle: 'IT Resume Examples & Templates | ApplyPro',
    metaDescription: 'Professional IT resume examples for software engineers, developers, data scientists, and more. ATS-optimized templates.',
    sortOrder: 1,
  },
  {
    name: 'Healthcare & Medical',
    slug: 'healthcare-medical',
    description: 'Medical professionals providing patient care and health services',
    icon: '🏥',
    color: '#EF4444',
    metaTitle: 'Healthcare Resume Examples & Templates | ApplyPro',
    metaDescription: 'Professional healthcare resume examples for nurses, doctors, medical assistants, and more.',
    sortOrder: 2,
  },
  {
    name: 'Finance & Accounting',
    slug: 'finance-accounting',
    description: 'Financial professionals managing money, investments, and fiscal operations',
    icon: '💰',
    color: '#10B981',
    metaTitle: 'Finance & Accounting Resume Examples | ApplyPro',
    metaDescription: 'Professional finance and accounting resume examples for CPAs, analysts, and financial managers.',
    sortOrder: 3,
  },
  {
    name: 'Sales & Marketing',
    slug: 'sales-marketing',
    description: 'Professionals driving revenue through sales and marketing strategies',
    icon: '📈',
    color: '#F59E0B',
    metaTitle: 'Sales & Marketing Resume Examples | ApplyPro',
    metaDescription: 'Professional sales and marketing resume examples for representatives, managers, and digital marketers.',
    sortOrder: 4,
  },
  {
    name: 'Engineering',
    slug: 'engineering',
    description: 'Engineers designing and building systems, structures, and products',
    icon: '⚙️',
    color: '#6366F1',
    metaTitle: 'Engineering Resume Examples & Templates | ApplyPro',
    metaDescription: 'Professional engineering resume examples for mechanical, civil, electrical engineers and more.',
    sortOrder: 5,
  },
  {
    name: 'Education',
    slug: 'education',
    description: 'Educators and academic professionals shaping future generations',
    icon: '📚',
    color: '#8B5CF6',
    metaTitle: 'Education Resume Examples & Templates | ApplyPro',
    metaDescription: 'Professional education resume examples for teachers, professors, tutors, and administrators.',
    sortOrder: 6,
  },
  {
    name: 'Legal',
    slug: 'legal',
    description: 'Legal professionals providing counsel and representation',
    icon: '⚖️',
    color: '#1F2937',
    metaTitle: 'Legal Resume Examples & Templates | ApplyPro',
    metaDescription: 'Professional legal resume examples for lawyers, paralegals, and legal assistants.',
    sortOrder: 7,
  },
  {
    name: 'Creative & Design',
    slug: 'creative-design',
    description: 'Creative professionals in design, art, and visual communications',
    icon: '🎨',
    color: '#EC4899',
    metaTitle: 'Creative & Design Resume Examples | ApplyPro',
    metaDescription: 'Professional creative resume examples for graphic designers, UX/UI designers, and artists.',
    sortOrder: 8,
  },
  {
    name: 'Customer Service',
    slug: 'customer-service',
    description: 'Professionals providing support and assistance to customers',
    icon: '🎧',
    color: '#06B6D4',
    metaTitle: 'Customer Service Resume Examples | ApplyPro',
    metaDescription: 'Professional customer service resume examples for representatives, managers, and call center agents.',
    sortOrder: 9,
  },
  {
    name: 'Human Resources',
    slug: 'human-resources',
    description: 'HR professionals managing talent and organizational development',
    icon: '👥',
    color: '#14B8A6',
    metaTitle: 'Human Resources Resume Examples | ApplyPro',
    metaDescription: 'Professional HR resume examples for recruiters, HR managers, and talent specialists.',
    sortOrder: 10,
  },
  {
    name: 'Administrative',
    slug: 'administrative',
    description: 'Administrative professionals supporting organizational operations',
    icon: '📋',
    color: '#64748B',
    metaTitle: 'Administrative Resume Examples | ApplyPro',
    metaDescription: 'Professional administrative resume examples for assistants, office managers, and executive assistants.',
    sortOrder: 11,
  },
  {
    name: 'Construction & Trades',
    slug: 'construction-trades',
    description: 'Skilled tradespeople in construction and building industries',
    icon: '🔨',
    color: '#D97706',
    metaTitle: 'Construction Resume Examples | ApplyPro',
    metaDescription: 'Professional construction resume examples for workers, managers, electricians, and contractors.',
    sortOrder: 12,
  },
  {
    name: 'Hospitality & Food Service',
    slug: 'hospitality-food-service',
    description: 'Hospitality professionals in hotels, restaurants, and food service',
    icon: '🍽️',
    color: '#DC2626',
    metaTitle: 'Hospitality Resume Examples | ApplyPro',
    metaDescription: 'Professional hospitality resume examples for chefs, hotel managers, servers, and caterers.',
    sortOrder: 13,
  },
  {
    name: 'Retail',
    slug: 'retail',
    description: 'Retail professionals in stores and consumer sales environments',
    icon: '🛒',
    color: '#7C3AED',
    metaTitle: 'Retail Resume Examples & Templates | ApplyPro',
    metaDescription: 'Professional retail resume examples for store managers, cashiers, and sales associates.',
    sortOrder: 14,
  },
  {
    name: 'Transportation & Logistics',
    slug: 'transportation-logistics',
    description: 'Professionals in transport, delivery, and supply chain management',
    icon: '🚚',
    color: '#0891B2',
    metaTitle: 'Transportation Resume Examples | ApplyPro',
    metaDescription: 'Professional transportation resume examples for drivers, logistics coordinators, and warehouse managers.',
    sortOrder: 15,
  },
  {
    name: 'Executive & Management',
    slug: 'executive-management',
    description: 'Senior leaders and executives driving organizational success',
    icon: '👔',
    color: '#1E3A8A',
    metaTitle: 'Executive Resume Examples | ApplyPro',
    metaDescription: 'Professional executive resume examples for CEOs, CFOs, directors, and senior managers.',
    sortOrder: 16,
  },
  {
    name: 'Production & Manufacturing',
    slug: 'production-manufacturing',
    description: 'Professionals in manufacturing and production environments',
    icon: '🏭',
    color: '#78716C',
    metaTitle: 'Manufacturing Resume Examples | ApplyPro',
    metaDescription: 'Professional manufacturing resume examples for production workers, machinists, and supervisors.',
    sortOrder: 17,
  },
  {
    name: 'Security & Protective Services',
    slug: 'security-protective-services',
    description: 'Security professionals protecting people and property',
    icon: '🛡️',
    color: '#374151',
    metaTitle: 'Security Resume Examples | ApplyPro',
    metaDescription: 'Professional security resume examples for guards, officers, and protective service professionals.',
    sortOrder: 18,
  },
  {
    name: 'Real Estate',
    slug: 'real-estate',
    description: 'Real estate professionals in property sales and management',
    icon: '🏠',
    color: '#059669',
    metaTitle: 'Real Estate Resume Examples | ApplyPro',
    metaDescription: 'Professional real estate resume examples for agents, brokers, and property managers.',
    sortOrder: 19,
  },
  {
    name: 'Social Work',
    slug: 'social-work',
    description: 'Social workers and counselors helping individuals and communities',
    icon: '💚',
    color: '#65A30D',
    metaTitle: 'Social Work Resume Examples | ApplyPro',
    metaDescription: 'Professional social work resume examples for social workers, counselors, and case managers.',
    sortOrder: 20,
  },
  {
    name: 'Beauty & Wellness',
    slug: 'beauty-wellness',
    description: 'Beauty and wellness professionals in spas, salons, and fitness',
    icon: '💅',
    color: '#DB2777',
    metaTitle: 'Beauty & Wellness Resume Examples | ApplyPro',
    metaDescription: 'Professional beauty resume examples for cosmetologists, spa managers, and wellness professionals.',
    sortOrder: 21,
  },
  {
    name: 'Sports & Fitness',
    slug: 'sports-fitness',
    description: 'Fitness and sports professionals in athletic and wellness industries',
    icon: '🏋️',
    color: '#EA580C',
    metaTitle: 'Sports & Fitness Resume Examples | ApplyPro',
    metaDescription: 'Professional fitness resume examples for personal trainers, coaches, and athletic professionals.',
    sortOrder: 22,
  },
  {
    name: 'Government & Public Sector',
    slug: 'government-public-sector',
    description: 'Public servants and government employees',
    icon: '🏛️',
    color: '#4338CA',
    metaTitle: 'Government Resume Examples | ApplyPro',
    metaDescription: 'Professional government resume examples for federal employees and public sector professionals.',
    sortOrder: 23,
  },
  {
    name: 'Maintenance & Repair',
    slug: 'maintenance-repair',
    description: 'Maintenance professionals keeping facilities and equipment running',
    icon: '🔧',
    color: '#57534E',
    metaTitle: 'Maintenance Resume Examples | ApplyPro',
    metaDescription: 'Professional maintenance resume examples for technicians, workers, and handymen.',
    sortOrder: 24,
  },
  {
    name: 'Student & Entry Level',
    slug: 'student-entry-level',
    description: 'Students, interns, and professionals starting their careers',
    icon: '🎓',
    color: '#2563EB',
    metaTitle: 'Student Resume Examples | ApplyPro',
    metaDescription: 'Professional student resume examples for interns, entry-level, and recent graduates.',
    sortOrder: 25,
  },
];

export const resumeExamples = [
  // (Abbreviated subset for maintainability; full dataset lives in prisma/seed-examples.ts)
  {
    categorySlug: 'information-technology',
    title: 'Software Engineer',
    slug: 'software-engineer',
    experienceLevel: 'MID',
    summary: 'Results-driven Software Engineer with 5+ years of experience designing, developing, and maintaining scalable software solutions. Proficient in full-stack development with expertise in JavaScript, Python, and cloud technologies. Strong problem-solving abilities and track record of delivering high-quality code on time.',
    bulletPoints: [
      'Developed and maintained 15+ microservices handling 1M+ daily requests with 99.9% uptime',
      'Led migration of legacy monolith to microservices architecture, reducing deployment time by 70%',
      'Implemented CI/CD pipelines using Jenkins and GitHub Actions, cutting release cycles from weeks to hours',
      'Mentored 5 junior developers, conducting code reviews and establishing best practices',
      'Optimized database queries resulting in 40% improvement in application response time',
    ],
    skills: ['JavaScript', 'TypeScript', 'Python', 'React', 'Node.js', 'AWS', 'Docker', 'Kubernetes', 'PostgreSQL', 'MongoDB', 'Git', 'Agile/Scrum'],
    metaTitle: 'Software Engineer Resume Example | ApplyPro',
    metaDescription: 'Professional software engineer resume example with ATS-optimized format. Get hired at top tech companies.',
    salaryRange: '$90,000 - $150,000',
    jobOutlook: '+22% growth by 2030',
    writingTips: [
      'Quantify achievements with metrics (users, performance improvements, cost savings)',
      'Highlight specific technologies and frameworks relevant to target role',
      'Include links to GitHub portfolio or live projects',
      'Use action verbs: Developed, Implemented, Optimized, Architected',
    ],
    commonMistakes: [
      'Listing technologies without context of how they were used',
      'Focusing on responsibilities instead of achievements',
      'Not customizing resume for each job application',
      'Omitting soft skills like teamwork and communication',
    ],
  },
  // ...additional examples omitted for brevity
];

export const skillSuggestions = [
  { name: 'JavaScript', category: 'Technical', relatedJobs: ['software-engineer', 'web-developer', 'full-stack-developer', 'frontend-developer'], popularity: 100 },
  { name: 'Python', category: 'Technical', relatedJobs: ['software-engineer', 'data-scientist', 'machine-learning-engineer', 'backend-developer'], popularity: 98 },
  { name: 'React', category: 'Technical', relatedJobs: ['software-engineer', 'web-developer', 'frontend-developer', 'full-stack-developer'], popularity: 95 },
  { name: 'Node.js', category: 'Technical', relatedJobs: ['software-engineer', 'web-developer', 'backend-developer', 'full-stack-developer'], popularity: 90 },
  { name: 'SQL', category: 'Technical', relatedJobs: ['software-engineer', 'data-scientist', 'data-analyst', 'database-administrator'], popularity: 92 },
  { name: 'TypeScript', category: 'Technical', relatedJobs: ['software-engineer', 'web-developer', 'frontend-developer'], popularity: 85 },
  { name: 'AWS', category: 'Technical', relatedJobs: ['software-engineer', 'devops-engineer', 'cloud-architect', 'solutions-architect'], popularity: 88 },
  { name: 'Docker', category: 'Technical', relatedJobs: ['software-engineer', 'devops-engineer', 'backend-developer'], popularity: 82 },
  { name: 'Kubernetes', category: 'Technical', relatedJobs: ['devops-engineer', 'cloud-architect', 'site-reliability-engineer'], popularity: 75 },
  { name: 'Git', category: 'Technical', relatedJobs: ['software-engineer', 'web-developer', 'devops-engineer'], popularity: 95 },
  { name: 'Communication', category: 'Soft Skills', relatedJobs: ['*'], popularity: 100 },
  { name: 'Problem Solving', category: 'Soft Skills', relatedJobs: ['*'], popularity: 98 },
  { name: 'Teamwork', category: 'Soft Skills', relatedJobs: ['*'], popularity: 95 },
];

// Note: `resumeExamples` here includes a representative subset to keep this shared file maintainable.
// The full set remains in `prisma/seed-examples.ts` for the complete seed run. If you prefer,
// move the entire `resumeExamples` array here and reference it from both places.
